### ISSUE TITLE
Implement Graph Cleaning Rules in Orion

### ISSUE THREAD

**Issue by capasfield** [RobokopU24/Issues#107]
From ARAGORN team meeting:https://docs.google.com/document/d/1x_ukP9eyy8ahb6ZlZAg78bdf6H2XxkcfGKR_r3WRcuM/edit?pli=1#

[DECISION] Let’s implement the graph cleaning rules in ORION.

**Comment by cbizon** [comment]
I'm not clear on what these rules were.  The link doesn't seem to go anywhere useful

**Comment by hina-shah** [comment]
Does not seem to be relevant anymore.
