### ISSUE TITLE
Funding statement 

### ISSUE THREAD

**Issue by karafecho** [RobokopU24/Issues#127]
This issue is to suggest an alignment of the funding statement on the main page of the ROBOKOP org (https://github.com/RobokopU24 - README) and on the question-builder page (https://qgraph.renci.org/question) with that on the ROBOKOP landing page (https://robokop.renci.org/).

**Comment by karafecho** [comment]
Note that the current funding statement on the ROBOKOP landing page contains two typos. (This may be fixed with next deployment).

1. National Center for Advancing Translational Science**s**
2. ExEmplar is not funded, and so this sentence can be removed: "ExEmPLAR is funded by XXX".

_ROBOKOP is a joint creation of the [Renaissance Computing Institute (RENCI)](https://renci.org/) at the [University of North Carolina at Chapel Hill](https://www.unc.edu/) and [CoVar LLC](https://covar.com/). The prototype was developed with funding from the [National Center for Advancing Translational Science](https://ncats.nih.gov/), National Institutes of Health (award [#OT2TR002514](https://taggs.hhs.gov/Detail/AwardDetail?arg_AwardNum=OT2TR002514&arg_ProgOfficeCode=264)). ROBOKOP's continued development is supported with joint funding from the [National Institute of Environmental Health Sciences](https://www.niehs.nih.gov/) and the [Office of Data Science Strategy](https://datascience.nih.gov/about/odss) within the [Institutes of Health](https://www.nih.gov/) (award [#U24ES035214](https://tools.niehs.nih.gov/portfolio/index.cfm?do=portfolio.grantDetail&grant_number=U24ES035214)). ExEmPLAR is funded by XXX_

I was asked to review a PR about the funding statement a few weeks ago and thought the issue had been resolved, but apparently, it has not.

**Comment by Woozl** [comment]
@karafecho thanks for reminding me of this yesterday, I remembered reading this last week, but for some reason, Github didn't put it in my inbox!

Good catch with the typos, I have made the requested changes, which should be visible on the [landing page](https://robokop.renci.org). Would you mind verifying the changes, and then notifying Chris so that he can copy it from the website into the Github organization README?

Regarding the question-builder in your first comment, I'm a bit confused, I thought we had already landed on an update, see here: https://github.com/RobokopU24/qgraph/pull/249

**Comment by karafecho** [comment]
Thanks, David. I noticed two things:

1. The link to the National Institutes of Health probably should be added to the first mention of NIH. (But this is a very picky comment.)
2. The second mention of NIH is written as "Institutes of Health" instead of "National Institutes of Health".

I think the fix to the question-builder page was not in place when I posted this ticket.

**Comment by karafecho** [comment]
Note that Chris and Alex may prefer to include the same funding statement across pages. We shall see.

**Comment by Woozl** [comment]
> 1. The link to the National Institutes of Health probably should be added to the first mention of NIH. (But this is a very picky comment.)
> 2. The second mention of NIH is written as "Institutes of Health" instead of "National Institutes of Health".

updated!
