### ISSUE TITLE
ExEmPLAR - capitalization

### ISSUE THREAD

**Issue by karafecho** [RobokopU24/Issues#129]
This issue is to suggest consistent capitalization of ExEmPLAR on the ROBOKOP landing page, across repos, and within all documentation.

**Comment by cbizon** [comment]
Is this still an issue?

**Comment by karafecho** [comment]
@Woozl : Perhaps you can update the text on the ExEmPLAR tile on the ROBOKOP landing page? I've addressed the issue in some (but not all) other places. Apart from the landing page update, I think we'll need to address the issue on a case-by-case basis.

**Comment by Woozl** [comment]
Yep, I can fix this

**Comment by hina-shah** [comment]
This was resolved by @Woozl

**Comment by karafecho** [comment]
Thank you.
