### ISSUE TITLE
Drop-down menu for nodes - remove non-existent choices - MVP1?

### ISSUE THREAD

**Issue by karafecho** [RobokopU24/Issues#138]
This issue is to suggest a potential MVP1 "must", namely, that the drop-down menu for node selection on ROBOKOP be stripped of all node choices that do not exist in the underlying KG. I posted a similar issue #98 for MYD88, but this issue is general and frustrating to users because: (1) it's hard to determine if your query is bad or your node choice is bad; (2) it's very unclear what node choice to select; (3) it's not intuitive for a user to just make another selection or enter a CURIE; and (4) it is time-consuming and therefore off-putting for users.

**Comment by cbizon** [comment]
I think this is a relatively high priority.  What we should do is get the identifiers out of robokop, and filter the nameres input files for those identifiers, then stand up our own nameres.

This has a disadvantage: every time we want to rebuild the graph, we need to add this step.  The other approach is to wrap the nameres in some filtering, but I think it borks the pagination, so I don't think it's worth pursuing.

**Comment by Woozl** [comment]
This was completed with the name resolver filtering upgrade
