### ISSUE TITLE
Node information

### ISSUE THREAD

**Issue by karafecho** [RobokopU24/Issues#141]
In examples such as this one, where there is no publication support, it would be helpful to be able to at least click on a node to get a bit more information, especially for uncommon nodes such as the gene _NR1l3_. Even if the CURIE is the only information returned, I think that would be helpful to users.

![image](https://user-images.githubusercontent.com/26254388/230645463-df60c058-8d7b-4ecd-bc7d-9b92ba8c38c4.png)

**Comment by karafecho** [comment]
Note that the issue above was identified when attempting to recreate the published findings posted to RobokopU24/Use-Cases#2.

**Isopropanol - Allergic Rhinitis**

*Published results*

![image](https://user-images.githubusercontent.com/26254388/230639550-88a49fc4-5e3d-4968-93e7-95b59c2f8f4f.png)

*New results*

*Note that in cases such as this one, where there is no publication support, it would be helpful to be able to at least click on a node to get a bit more information, especially for uncommon nodes such as the gene NR1l3. [What is the NR3c1 gene responsible for? NR3c1 is thought to be involved in regulation of the hypothalamic-pituitary-adrenal (HPA) axis by modulating availability of the stress hormone cortisol.]*

![image](https://user-images.githubusercontent.com/26254388/230642470-21b237b4-b926-486b-8adc-d8e5bafdf567.png)

![image](https://user-images.githubusercontent.com/26254388/230642686-8edc5fb8-d3c4-4c3a-ba3f-d81088a7798f.png)

**Comment by cbizon** [comment]
I think we could do this via linkouts based on the equivalent identifiers

**Comment by Woozl** [comment]
closed by https://github.com/RobokopU24/qgraph/commit/412cda729a6aceb3fb3054f56f5e983a5a86bd53
