### ISSUE TITLE
Subclass diseases do not make sense

### ISSUE THREAD

**Issue by karafecho** [RobokopU24/Issues#142]
The following query is returning results that include diseases other than cardiovascular disorders: polybrominated diphenyl ether - related_to - Gene - related_to - cardiovascular disorder. For example, the top answer is for complete gonadal dysgenesis.

![image](https://user-images.githubusercontent.com/26254388/230651146-6f444f62-6a77-4be0-8adb-99179b3a41f0.png)

**Comment by karafecho** [comment]
Also see #139.

**Comment by cbizon** [comment]
Complete Gonadal Dysgenesis is a subclass of cardiovascular disease in MONDO:
![image](https://user-images.githubusercontent.com/10744350/231240271-0295d66a-3efc-44da-9b0e-5c62673aacc5.png)

**Comment by cbizon** [comment]
So I'm not sure that this is a problem?

**Comment by karafecho** [comment]
Interesting. I had looked up complete gonadal dysgenesis before posting this ticket and did not see an obvious relationship to cardiovascular disorder. I just checked Orphanet's hierarchy and it, too, lists complete gonadal dysgenesis as a rare cardiac disease: https://www.orpha.net/consor/cgi-bin/Disease_Classif.php?lng=EN&data_id=146&PatId=1044&search=Disease_Classif_Simple&new=1. So, I guess this result is accurate.

There are three publications supporting the decabromodiphenyl oxide - _NR5A1_ edge. There isn't any publication support for the _NR5A1_ - complete gonadal dysgenesis edge, but Pharos is making the assertion and OmniCorp is supporting it with 45 co-occurrences, so I suppose the edge is sufficiently supported. 

I'd be curious to: (1) compare these results (automat.renci.org/#/robokopkg) with those from ExEmPLAR (robokopkg.renci.org) and (2) get a reaction from the expert who submitted the question, as she was interested in cardiotoxicity (which I was unable to include as a node - I tried a bunch of entities/CURIES), but I'm guessing this answer, while valid, wouldn't align with her expectations/interests. Then again, I'm not sure it's worth sharing these results, as one might argue that the query didn't accurately capture the question.

In some sense, this issue relates to the 'subclass' issues noted in #139 and elsewhere.

**Comment by karafecho** [comment]
ExEmPLAR results (for comparison):

![image](https://user-images.githubusercontent.com/26254388/231494179-bf1923bf-33ea-4939-9ebd-67638d6bb8f0.png)

![image](https://user-images.githubusercontent.com/26254388/231494643-9500b911-07a8-4e6e-9ea8-a432e145ad7b.png)

**Comment by karafecho** [comment]
ROBOKOP results for decabromodiphenyl oxide only:

![image](https://user-images.githubusercontent.com/26254388/231498204-fa8affdf-dcdb-488f-a684-5ac0438deadb.png)

**Comment by cbizon** [comment]
Exemplar (IIRC) is doing a text based search for nodes.    It is not reasoning over subclass of edges, nor is it using identifiers.   So there will be differences based on those things.

Is the issue here that we just don't like this subclass result?  To some degree we're at the mercy of what the data says.  The only other way I can think to affect this is by downweighting edges that are supported by subclass of inferences.

**Comment by karafecho** [comment]
Yes, I completely expect differences between ROBOKOP and ExEmPLAR (they aren't even querying the same KG); I was just comparing the two result sets, as noted.

I think we need to provide users with control over subclass inferences, especially when high-level nodes such as "cardiovascular disorder" are selected. I will close this ticket and comment on #139.
