### ISSUE TITLE
Unify robokop Kg and robokopkg graphs.

### ISSUE THREAD

**Issue by karafecho** [RobokopU24/Issues#143]
Please see my last two posts in RobokopU24/Use-Cases#10. I haven't been able to replicate Jon-Michael's ExEmplar results using ROBOKOP qgraph. Note that the screenshots I captured include only a few of the queries I tried. In addition to testing a variety of predicates and nodes (e.g., herpes zoster vs shingles), I tested several different chemical entity selections (i.e., from the duplicates in the drop-down list).

I'm not expecting results for all five of the input chemical entities, but I wouldn't think that would break a query.

Subsequent troubleshooting with Jon-Michael revealed the following.

This ExEmplar query hits the ROBOKOP KG Neo4j db directly and returns results:

![image](https://user-images.githubusercontent.com/26254388/230685623-fc4955dd-901d-40b9-afb0-70615c223615.png)

This ROBOKOP qgraph query does not return results:

![image](https://user-images.githubusercontent.com/26254388/230685658-b95ab76d-1960-4058-9433-da38629a4f30.png)

Same query as the ExEmplar one, but run in the Neo4j browser, with results returned:

![image](https://user-images.githubusercontent.com/26254388/230685725-f39ea9d3-ba88-4980-af22-8572265ab705.png)

Same query as the ExEmplar one, but posted to ROBOKOP KG on Automat, with no results returned:

![image](https://user-images.githubusercontent.com/26254388/230686297-ca79aa50-2792-4f18-80ba-0e31b52810f6.png)

I'm thinking this might be a Cypher to ROBOKOP qgraph / TRAPI translation issue?

**Comment by EvanDietzMorris** [comment]
This was due to content differences between the graphs hosted at robokopkg.renci.org (the graph exemplar queried) and robokopkg on Automat (the graph qgraph queried).

**Comment by karafecho** [comment]
I think this needs to be reconciled. We should not have two different versions of ROBOKOP KG.

**Comment by karafecho** [comment]
Moreover, we've branded robokopkg.renci.org as _the_ ROBOKOP KG, so that endpoint should be ground truth.

**Comment by karafecho** [comment]
**Decision on 04/10/2023:** robokopkg.renci.org and http://automat.renci.org/#/robokopkg will point to duplicate copies of a new ROBOKOP KG that will include the existing Automat ROBOKOP KG plus Text Miner KG (but not CORD19 KG).

**Comment by cbizon** [comment]
I think that this has been implemented.
