### ISSUE TITLE
Copy JSON button doesn't work

### ISSUE THREAD

**Issue by karafecho** [RobokopU24/Issues#144]
This issue is to report that the copy feature within the ROBOKOP Query Graph JSON Editor does not appear to work.

![image](https://user-images.githubusercontent.com/26254388/230972658-f651c42e-6905-42fa-8de2-ec624ddcfa3c.png)

**Comment by cbizon** [comment]
It seems to work for me using mac/chrome.   That's how I was getting the sample query JSONs.

**Comment by karafecho** [comment]
I just tried it again ... and it works. Not sure why I had trouble previously.

Closing ticket, as there is no issue to resolve ...

**Comment by EvanDietzMorris** [comment]
For me this works on Chrome but not Firefox.. I'm on a mac..

**Comment by karafecho** [comment]
Actually, that might explain the issue I had the other day, as I may have been working from a coffee shop on my surface device. I'd have to test that theory (browser/device differences), but I guess my question is does the browser/device/os system incompatibility matter? In other words, is this something that needs to be addressed or simply noted, perhaps somewhere in the documentation?

**Comment by karafecho** [comment]
I (unintentionally) confirmed that this indeed is the case: the copy feature works on Chrome but not on Firefox, regardless of device/os system.

**Comment by Woozl** [comment]
Fixed in https://github.com/RobokopU24/qgraph/pull/253
