### ISSUE TITLE
RENCI SRI Reference KG

### ISSUE THREAD

**Issue by karafecho** [RobokopU24/Issues#145]
This issue is to suggest that we remove RENCI SRI Reference KG from the Automat landing page.

**Comment by EvanDietzMorris** [comment]
This is a bit confusing - RENCI SRI Reference KG is our parsing of the SRI Reference KG, which we have called "Biolink", which led to some confusion and @karafecho wrote up a description for the biolink model, which we do not have a plater or KG for. I wrote that title and description as a placeholder, but it could be improved obviously. This is a source we include in the ROBOKOP KG though.

**Comment by karafecho** [comment]
I agree that this is confusing. The Automat landing page now lists both SRI Reference KG and RENCI SRI Reference KG. I assume you would not include both in the ROBOKOP KG? If that's the case, then perhaps you can remove one or the other?

I will update the description when I proofread and finalize the Automat descriptions.

**Comment by cbizon** [comment]
What does our parsing do?

**Comment by cbizon** [comment]
Are we satisfied with the current setup or is there more work to do here?

**Comment by karafecho** [comment]
Sort of. We still have two different SRI Reference KGs exposed as Automats: RENCI SRI Reference KG and SRI Reference KG. I don't think we need to expose the RENCI SRI Reference KG, although I suppose it isn't confusing or damaging to do so, unlike the Ubergraph and Ubergraph Redundant issue. I'll defer to @EvanDietzMorris .

**Comment by EvanDietzMorris** [comment]
This is not resolved - we are no longer hosting the RENCI version of monarch KG as a standalone Plater, we changed the name of the actual graph to monarch KG, it looks like the UI was not updated to reflect either change.
