### ISSUE TITLE
where are the predicates?

### ISSUE THREAD

**Issue by cbizon** [RobokopU24/Issues#149]
I wanted to run a "treats" query but treats did not show up as a predicate.  Also, I could not get "associated with".   There could be a couple of reasons for this...

One possibility is that there is a BMT lite instance in there that needs to be updated (or some other way of pulling in a version of biolink model that needs to be updated)

Another is that there is some kind of domain range constraint that maybe is to strong being applied.

**Comment by Woozl** [comment]
@cbizon could you provide which query you were attempting? I can see `treats` depending on which nodes the edge is connected to:

![image](https://user-images.githubusercontent.com/16181779/232551572-8e8d0793-7d49-42c1-ba62-b3b83ddeebe0.png)

For reference, here is the relevant code filtering the predicates:

https://github.com/RobokopU24/qgraph/blob/8caababfbbce66eb29adb87ff43606c8aafe5ee5/src/pages/queryBuilder/textEditor/textEditorRow/PredicateSelector.jsx#L25-L53

**Comment by Woozl** [comment]
Actually, now I see that if you make the query more general, it doesn't always show up. For instance, changing "Levodopa" to "Drug"

**Comment by Woozl** [comment]
closed by https://github.com/RobokopU24/qgraph/pull/254
