### ISSUE TITLE
ROBOKOP only has one node/edge for "biolink:Drug" category.

### ISSUE THREAD

**Issue by beasleyjonm** [RobokopU24/Issues#151]
Biolink:Drug is one of the node types in ROBOKOP, yet only one node exists with this typing (see the attached screenshot). The only triple containing this node is coming from drugcentral.

I worry that a new user may pose a simple query, such as "What 'biolink:Drug' treats a disease?" and they will get no results back. This could be very confusing and discouraging to a naive user. 

One can still filter for "drugs" by using CHEBI roles or looking for nodes with FDA labels. For example, "MATCH (d:`biolink:ChemicalEntity`) WHERE d.fda_labels IS NOT NULL OR  (d.CHEBI_ROLE_pharmaceutical)=true RETURN count(d)" finds 5985 ChemicalEntity nodes with those properties.

Chris suggested it may be best to just remove this biolink:Drug label from the graph completely for now until a longer term solution is found.

**Comment by cbizon** [comment]
Yeah the confusion is that what is meant by Drug in biolink is something more like an RXNORM id: a particular formulation like Pfizer's 80 mg Liptor.  Usually what we want to talk about is the active ingredient of Atorvastatin.   Mostly, we have just not added drug nodes, as there is not much interesting (for us) to say about different doses or formulations.  

Probably the cleanest way to handle this is to add conflation for chemicals and drugs to Babel/NodeNorm.

**Comment by beasleyjonm** [comment]
Thank you, this makes things much clearer to me!

**Comment by cbizon** [comment]
I think we want to ensure that chemical/drug conflation is turned on for the name res.  Do we know if this is the case?

**Comment by hina-shah** [comment]
Is this still an issue?

**Comment by beasleyjonm** [comment]
I believe this issue is fixed, but I'm not exactly sure what changes affected this. Now, I am seeing 2487 biolink:Drug nodes in the graph.

**Comment by EvanDietzMorris** [comment]
This issue can be closed. Drug chemical conflation was implemented in Babel/Node Norm and so robokopkg contains more "Drugs" now. Name res also implicitly performs drug chemical conflation now (the look up is built on conflated names) so that should work as well.
