### ISSUE TITLE
Redesign question-builder page

### ISSUE THREAD

**Issue by karafecho** [RobokopU24/Issues#154]
As Alex noted, and I agree with, the ROBOKOP question-builder page is kind of a disappointment after visiting the spiffy main landing page. I'd suggest that this be redesigned as follows:

1. Increase the font size and general width of the header, including all buttons, using a color scheme for the text and background that matches that on the main landing page.
2. Consider repositioning the buttons, perhaps as a column on the left, similar to the main landing page.
3. Replace the text "ROBOKOP" with the ROBOKOP logo from the main landing page. 
4. I don't know what this is called, but for the tab display, use the same one that is used on the main landing page (see below).
5. Increase the font size for the funding statement.

While these are largely aesthetic changes, I think they're important, as they impact user (and funder) impression. Moreover, if the question-builder page looks professional, then users will be willing to spend some time playing around with queries; if the page looks amateur, then users are likely to quit the very first time they become frustrated.

That said, I don't know how difficult it is to make the changes I'm suggesting.

![image](https://user-images.githubusercontent.com/26254388/231592015-af69439a-5c44-4129-9c16-a2b3a69e745b.png)

**Comment by Woozl** [comment]
I've implemented 3, 4, and 5 in https://github.com/RobokopU24/qgraph/pull/253. These are also live now: [qgraph.renci.org](https://qgraph.renci.org).

@karafecho could you elaborate what you mean about 1? Do you mean just making the links all uppercase and increasing the font size?

**Comment by karafecho** [comment]
I think this may be easier to discuss via Zoom, just so I can show you what I mean. Also, I don't see the fixes for 4 and 5. But let's try to schedule a short (15-minute) call.

**Comment by Woozl** [comment]
The first bullet has been implemented

https://github.com/RobokopU24/qgraph/pull/253/commits/b22092ef45e8e1d9358646e15c35a083b483f2eb
