### ISSUE TITLE
Revised Automat landing page text

### ISSUE THREAD

**Issue by karafecho** [RobokopU24/Issues#155]
I revised the text descriptions for knowledge sources on the Automat landing page. See [this doc](https://docs.google.com/document/d/1K34gf5I2MbYo067IswHcplS9kYxCz0Ii4cMOJIx3t3k/edit?usp=sharing). There are quite a few edits, so I'm not sure how we should proceed with updating the existing text descriptions. It may be easiest to "accept all changes" and then copy and paste each description. I am happy to help with this, if someone can point me in the right direction. Just let me know.

@EvanDietzMorris : Note that the only two title changes that will need to be fixed on the backend are a correction to "IntAct Molecular Interactions Database" and "ICEES KG" and the addition of "Text Mining Provider KG".

**Comment by EvanDietzMorris** [comment]
These changes should be included in the latest metadata on our new u24 automat. Let me know if something is not right and we can change the metadata in place.
