### ISSUE TITLE
Revised About ROBOKOP page

### ISSUE THREAD

**Issue by karafecho** [RobokopU24/Issues#156]
This issue is to request that the text on the existing About ROBOKOP page be replaced with the revised text that I drafted. Please see [this doc](https://docs.google.com/document/d/1TurMi1GM7chhZ4fHT9iI93hUwjflfLWP/edit?usp=sharing&ouid=112054006232285231595&rtpof=true&sd=true). I'm not sure if this is possible, but it would be great to add the ROBOKOP logo, perhaps to the top left corner of the page, just for consistency.

**Comment by Woozl** [comment]
I've updated the about page text content, since #154 also tracks the logo addition, I'm going to close this as completed
