### ISSUE TITLE
Revised Quick Start Guide page

### ISSUE THREAD

**Issue by karafecho** [RobokopU24/Issues#157]
This issue is to request that the text on the existing ROBOKOP Quick Start Guide page be replaced with the revised text that I drafted. Please see [this doc](https://docs.google.com/document/d/1rcDDhQa64FOEWPOVAS9ZD6olvwVjm3_A/edit?usp=sharing&ouid=112054006232285231595&rtpof=true&sd=true). I'm not sure if this is possible, but it would be great to add the ROBOKOP logo, perhaps to the top left corner of the page, just for consistency.

**Comment by Woozl** [comment]
Just updated this text. The only thing I modified was under the "Find Additional User Documentation", where I removed this text:

> Users who are seeking additional information can ~~review a ROBOKOP tutorial or~~ refer to the publications below.

as I'm not currently sure where those tutorials are or if they exist. We can reopen this issue or start a new one with the info when available
