### ISSUE TITLE
Lots of bidirectional has_phenotypes

### ISSUE THREAD

**Issue by cbizon** [RobokopU24/Issues#160]
In robokop: 
```
match (a:`biolink:NamedThing`)-[x:`biolink:has_phenotype`]->(b)-[y:`biolink:has_phenotype`]->(a) return * limit 10
```

Returns plenty:
![image](https://user-images.githubusercontent.com/10744350/232539802-68414890-0d03-407c-ac05-35b94df07d37.png)

All of them look like one direction is coming from the SRI graph and the other is coming from hetio.  That suggests to me that one of them is being inverted on load (probably hetio?)

**Comment by EvanDietzMorris** [comment]
Unfortunately it's not as simple as an inversion. Hetio has 16,570 has_phenotype edges, 7,459 of them are coming from MEDLINE Co-Occurrences (MRCOC), which if I understand correctly are literature co-occurrences that don't really say anything about directionality, but Hetio has necessarily assigned one (probably arbitrarily). All of the other examples of has_phenotype in Hetio I've looked at seem to have the correct directionality.

Should we throw out the MEDLINE edges? Change the predicate to correlated_with for those?

**Comment by cbizon** [comment]
I think throw them out

**Comment by EvanDietzMorris** [comment]
There is a filter in the parser now that removes them.
