### ISSUE TITLE
Revised ROBOKOP Tutorial

### ISSUE THREAD

**Issue by karafecho** [RobokopU24/Issues#162]
This issue is to request that a link to the ROBOKOP Tutorial is added to the ROBOKOP question-builder page. The text can be found [here](https://docs.google.com/document/d/1yfnpLmsAK3Qy2x0ItVl9RSIttfWn2KCK/edit?usp=sharing&ouid=112054006232285231595&rtpof=true&sd=true). Note that the page breaks were included only for convenience when creating the page and can be deleted.

**Comment by Woozl** [comment]
closed in https://github.com/RobokopU24/qgraph/pull/253. Viewable on the live site: https://qgraph.renci.org/tutorial

**Comment by karafecho** [comment]
This looks great! However, I think we need to include a button/link to "Tutorial" next to the "About" and "Guide" buttons/links.

**Comment by Woozl** [comment]
Added tutorial to header: https://github.com/RobokopU24/qgraph/pull/253/commits/08bdb58ae2f4118cf79e5f0dfe11067821a73dc4
