### ISSUE TITLE
Incorrect hyperlink on ROBOKOP question-builder page

### ISSUE THREAD

**Issue by karafecho** [RobokopU24/Issues#164]
This issue is to report that the hyperlink for NIEHS on the ROBOKOP question-builder page is incorrect. It should be https://www.niehs.nih.gov/ not https://qgraph.renci.org/question.

**Comment by Woozl** [comment]
Fixed in https://github.com/RobokopU24/qgraph/pull/253 


https://github.com/RobokopU24/qgraph/pull/253/commits/bea04da37aa7ea3de2955fe81bc15aea58630b5c
