### ISSUE TITLE
Cache Question Builder sample query results

### ISSUE THREAD

**Issue by karafecho** [RobokopU24/Issues#173]
This issue is to suggest that we cache the (five) sample queries that are provided on the Question Builder page. The reason is to better enable live demos, so that the audience isn't waiting (valuable) minutes for a result set to load and the presenter isn't trying to explain the issue and simultaneously redirect the audience's attention.

**Comment by Woozl** [comment]
https://github.com/RobokopU24/qgraph/pull/265
