### ISSUE TITLE
Link to RoboDocumentation on ROBOKOP UI page

### ISSUE THREAD

**Issue by dnwillia23** [RobokopU24/Issues#175]
On the ROBOKOP landing page (https://robokop.renci.org/), we suggested at the July 24 meeting adding a link to the RoboDocumentation repo under `Additional Tools`.  Can you please add a tab for `RoboDocumentation` pointing to this link: `https://github.com/RobokopU24/RoboDocumentation`?

**Comment by Woozl** [comment]
closed by https://github.com/RobokopU24/landing-page/commit/53c9950b04be3bf4623488cd07db64582ff5bc48
