### ISSUE TITLE
Change text description of CAM Provider KG

### ISSUE THREAD

**Issue by karafecho** [RobokopU24/Issues#188]
This issue is to request a change in the description of the Automat CAM Provider KG. Specifically, please (1) fix the typo in "CAMP Provider KG" (should be CAM not CAMP) and (2) rename "CAM Provider KG" as "CAM KG", for consistency with the other Automat KGs.

Here's the current description:

![image](https://github.com/RobokopU24/landing-page/assets/26254388/ec740a96-16bc-4579-86d8-310880126fb4)

**Comment by EvanDietzMorris** [comment]
I'm rebuilding CAM KP this week and will get these changes included.

**Comment by cbizon** [comment]
Is this complete? @EvanDietzMorris  if so please close.

**Comment by karafecho** [comment]
I just checked. This issue was partially addressed. The tile title still needs to be updated to "CAM KG".
