### ISSUE TITLE
Deprecate automat-renci-sri-reference-kg, replace automat-sri-reference-kg with automat-monarchinitiative

### ISSUE THREAD

**Issue by karafecho** [RobokopU24/Issues#189]
This issue reflects recent discussions and decisions made by Kara, Evan, Chris, Sierra, and others. Specifically, we decided to deprecate automat-renci-sri-kg and replace automat-sri-reference-kg with automat-monarchinitiative (or automat-monarchinitiative-kg).

@EvanDietzMorris : Does this sound right?

**Comment by EvanDietzMorris** [comment]
That's right - I don't think @Woozl needs to do anything here, these changes will come along with the next round of graph/metadata deployments.
