### ISSUE TITLE
Remove self-subclasses

### ISSUE THREAD

**Issue by hina-shah** [RobokopU24/Issues#194]
To reproduce:
In question builder, try submitting a query "asthma" relates to "asthma". This will create a result table, and one of the rows should be from asthma to asthma. If you click on the row it looks like here in the image:

<img width="508" alt="image" src="https://github.com/RobokopU24/Feedback/assets/22948571/70ff16c2-448a-4af0-8fb6-1adee4f548a5">

**Comment by cbizon** [comment]
I think we should filter out A - subclass-of - A edges somewhere.  Logically true; totally useless.

**Comment by EvanDietzMorris** [comment]
Is this something we could apply more generally? Are there any A-->A edges in robokop we care about? The issue is complicated by the fact that this can occur during normalization.

**Comment by cbizon** [comment]
I think that there are probably self-interaction or self-regulation edges that we would want to keep

**Comment by EvanDietzMorris** [comment]
cool, I think if we want zero A-subclass_of-A edges we can pretty easily apply that in normalization by default, but it should probably be it's own operation that can be specified in the graph spec

**Comment by EvanDietzMorris** [comment]
This is implemented in ORION now, subclass loop edges are removed from robokopkg.
