### ISSUE TITLE
UI dropdown menu selections for nodes

### ISSUE THREAD

**Issue by karafecho** [RobokopU24/Issues#200]
This issue is to consider the way we are displaying node options in the UI. Specifically, sometimes numerous options are available, e.g., PPARA, but how is a user supposed to know which option to select? What if they don’t care? We've discussed this before, but I don't believe we have a concrete plan in place. I think it's time to develop a plan, as this issue frustrates external users (not to mention, me).

**Comment by EvanDietzMorris** [comment]
This is a bit more complicated than it sounds.. we could pretty easily show the node types for IDs that come back from name resolution, but for example in the PPARA case, that wouldn't be much more helpful, it would just show that they are a bunch of genes. 

More helpful information might be:
- taxon, which are currently not included in name res / node norm. In theory we could add that when we build our custom version of name res from robokop node properties, but not all nodes have species information, nor is it in a consistent format currently
- number of edges connected to the node in the graph (which is not currently available anywhere but could be)

I also think it may be confusing to have one text entry field that can be used to select node identifiers OR node types. ie if you type in Gene are you looking for nodes with the type Gene or a node named Gene. Possibly we should have another drop down or something like that which is to select the type of node information you are about to enter in the auto select field, which would then limit results to that type.

AFAIK we also don't have a way to specify multiple nodes (the case where the user doesn't care which). That would be doable in the TRAPI but I'm not sure how it would look in the UI.

**Comment by karafecho** [comment]
Thanks for the quick feedback, Evan.

Yes, I agree that showing node types for IDs isn't very helpful.

I'm not sure including the taxon is worth the effort, for the reasons you note, but I do think it might be helpful to include the number of edges connected to a node in the KG, although a user's natural inclination (I think) would be to choose the most highly connected nodes, thus excluding less connected nodes that may actually be more informative.

To your last two points, I'm not sure how best to support the AND and/or the OR option in the UI, but I do think it would be valuable to users. As is, a user _can_ specify multiple nodes of the same type connected to some other entity, but it's very clumsy. I wonder if it makes sense to not worry about the UI display for now and just include a sample JSON query that supports multi-CURIE queries?

Just a few thoughts ...

**Comment by cbizon** [comment]
In the old robokop UI including number of edges was incredibly useful.   You're right Kara that you might miss something, but either one you choose you miss something, and this lets you miss less stuff.  Also see that we now have an issue for adding taxon, which I think is actually extremely helpful when it comes to choosing genes (since that is what actually distinguishes the choices)
