### ISSUE TITLE
Add qualifiers to the query

### ISSUE THREAD

**Issue by cbizon** [RobokopU24/Issues#210]
There is no way currently to ask basic questions like "what gene upregulates this other gene"?   Or "what chemical increases expression of that gene"?

**Comment by Woozl** [comment]
This is closed at a basic level by https://github.com/RobokopU24/qgraph/pull/284 (also developed in this [demo app](https://github.com/RobokopU24/biolink-triple-demo)) and is now merged into the production version of the UI. I will create more detailed issues of the places that need to be improved.
