### ISSUE TITLE
binds is deprecated

### ISSUE THREAD

**Issue by cbizon** [RobokopU24/Issues#219]
We are returning `biolink:binds` as a predicate 

```
Edge has deprecated predicate
			$ infores:bindingdb -> infores:automat-robokop -> infores:aragorn
				# biolink:binds
```

We need to find out what this has been replaced with and update.

**Comment by cbizon** [comment]
Linking to https://github.com/NCATSTranslator/Feedback/issues/811

**Comment by eKathleenCarter** [comment]
Three sources have the predicate biolink: binds, Binding-DB, DrugCentral, and GtoPDB. 

I'll look into these and see what they need to be replaced with.
