### ISSUE TITLE
zip node/edge files?

### ISSUE THREAD

**Issue by cbizon** [RobokopU24/Issues#223]
Downloading robokop edges and nodes are slow, should they be gzipped?

**Comment by EvanDietzMorris** [comment]
Yea that makes sense, we could gzip nodes and edges together or separately.. gzipping the neo4j dump would also make sense for downloading purposes but means it would need to be decompressed during plater deployment

**Comment by EvanDietzMorris** [comment]
I'm using gzip on the nodes and edges files now, in the script I use to move them to the public server.
