### ISSUE TITLE
Footer overlapping with buttons

### ISSUE THREAD

**Issue by EvanDietzMorris** [RobokopU24/Issues#224]
For the question builder, on smaller screen sizes (but not even very small) the footer can overlap with the buttons below the question-builder in a problematic way. It's possible to not even see them when the page loads, but more importantly, impossible to scroll down to access them. Maybe we just need some padding below the buttons or something?

**Comment by Woozl** [comment]
https://github.com/RobokopU24/qgraph/pull/285 this should prevent the footer from ever overlapping with anything
