### ISSUE TITLE
Multiple (identical?) MYD88 input choices

### ISSUE THREAD

**Issue by karafecho** [RobokopU24/Issues#98]
This issue is to report that multiple, apparently identical (except for perhaps the underlying CURIE?) appear in the drop-down menu when searching for "MYD88". Note that even if the choices differ by underlying CURIE, this makes it difficult for users to determine the correct choice.

![image](https://user-images.githubusercontent.com/26254388/212166913-84bc691a-e4fa-47d4-872e-53057374608b.png)

**Comment by cbizon** [comment]
This will be fixed by #205

**Comment by Woozl** [comment]
Closed by https://github.com/RobokopU24/qgraph/commit/f31f7dff13eb3f9b5028c8291830c470b531811b and https://github.com/TranslatorSRI/NameResolution/pull/143
